### ISSUE TITLE
Add HTTPS support back to openConnection

### ISSUE THREAD

**Issue by MichaelKing1832** [lart2150/kmttg#2]
I noticed the remark "switch to http client due to limited default https ciphers for url openConnection."
Is this buried in the http library jars in lib? Can they be upgraded/updated? 
Can they be unpacked into the project so we can look closer at the connection factory constructor to support HTTPS?
I have some background in this area.

**Comment by lart2150** [comment]
It's the github requests in update.java and config.java for this commit
https://github.com/lart2150/kmttg/commit/be0de2b27738d76f2a0c49ecb2266e971a29eb75

I still need the other http library for the network requests I make to get the domain token.  I decided since I already had a more feature rich client with better tsl defaults I would just use it.

**Comment by MichaelKing1832** [comment]
Thanks for the link to the commit, and I see what you did there. 😉

The extra code and elbow grease to switch to the Apache HTTPS client is very much appreciated.

Especially as that client component will automatically take advantage of TLS1.3 and HTTPS/2 improvements as they are adopted by the hosting services of remote resources/external dependencies.
